### ISSUE TITLE
Cannot get AllPixel working

### ISSUE THREAD

**Issue by danawoodman** [ManiacalLabs/AllPixel#9]
I've followed the directions as closely as I can but still cannot light up my LEDs.

- AllPixelMini
- LEDS: WS2812B
- OSX High Sierra 10.13.6
- Python 3.7.0
- PIP 18.0

Using sample program from Wiki:

```python
import bibliopixel
# causes frame timing information to be output
bibliopixel.log.setLogLevel(bibliopixel.log.DEBUG)

# Load driver for the AllPixel
from bibliopixel.drivers.serial import *
# set number of pixels & LED type here
driver = Serial(num = 10, ledtype = LEDTYPE.WS2812B)

# load the LEDStrip class
from bibliopixel.layout import *
led = Strip(driver)

# load channel test animation
from bibliopixel.animation import StripChannelTest
anim = StripChannelTest(led)

try:
    # run the animation
    anim.run()
except KeyboardInterrupt:
    # Ctrl+C will exit the animation and turn the LEDs offs
    led.all_off()
    led.update()
```

I am getting the following error:

```bash
WARNING - deprecated - util.setLogLevel
INFO - devices - Using COM Port: /dev/cu.usbmodem23451, Device ID: 0, Device Ver: 0
WARNING - deprecated - BaseAnimation.run
DEBUG - animation_threading - Animation starts on main thread
Traceback (most recent call last):
  File "leds.py", line 23, in <module>
    anim.run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py", line 202, in run
    self.start()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py", line 108, in start
    self.threading.start()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/util/threads/animation_threading.py", line 78, in start
    self.target()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/util/threads/animation_threading.py", line 38, in target
    self.run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py", line 117, in run_all_frames
    for i in self.generate_frames():
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py", line 121, in generate_frames
    self._pre_run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py", line 171, in _pre_run
    self.runner.run_start_time = self.project.time()
AttributeError: 'NoneType' object has no attribute 'time'
```

Any idea what I could be doing wrong? Something I'm missing? 

Thanks!

**Comment by adammhaile** [comment]
That's very odd... What's the actual command you are running?

On Sep 23, 2018 11:18 PM, "Dana Woodman" <notifications@github.com> wrote:

I've followed the directions as closely as I can but still cannot light up
my LEDs.

   - AllPixelMini
   - LEDS: WS2812B
   - OSX High Sierra 10.13.6
   - Python 3.7.0
   - PIP 18.0

Using sample program from Wiki:

import bibliopixel# causes frame timing information to be output
bibliopixel.log.setLogLevel(bibliopixel.log.DEBUG)
# Load driver for the AllPixelfrom bibliopixel.drivers.serial import
*# set number of pixels & LED type here
driver = Serial(num = 10, ledtype = LEDTYPE.WS2812B)
# load the LEDStrip classfrom bibliopixel.layout import *
led = Strip(driver)
# load channel test animationfrom bibliopixel.animation import StripChannelTest
anim = StripChannelTest(led)
try:
    # run the animation
    anim.run()except KeyboardInterrupt:
    # Ctrl+C will exit the animation and turn the LEDs offs
    led.all_off()
    led.update()

I am getting the following error:

WARNING - deprecated - util.setLogLevel
INFO - devices - Using COM Port: /dev/cu.usbmodem23451, Device ID: 0,
Device Ver: 0
WARNING - deprecated - BaseAnimation.run
DEBUG - animation_threading - Animation starts on main thread
Traceback (most recent call last):
  File "leds.py", line 23, in <module>
    anim.run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py",
line 202, in run
    self.start()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py",
line 108, in start
    self.threading.start()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/util/threads/animation_threading.py",
line 78, in start
    self.target()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/util/threads/animation_threading.py",
line 38, in target
    self.run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py",
line 117, in run_all_frames
    for i in self.generate_frames():
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py",
line 121, in generate_frames
    self._pre_run()
  File "/usr/local/lib/python3.7/site-packages/bibliopixel/animation/animation.py",
line 171, in _pre_run
    self.runner.run_start_time = self.project.time()
AttributeError: 'NoneType' object has no attribute 'time'

Any idea what I could be doing wrong? Something I'm missing?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ManiacalLabs/AllPixel/issues/9>, or mute the thread

**Comment by danawoodman** [comment]
`python myfile.py`

**Comment by danawoodman** [comment]
FWIW I have the latest BiblioPixel as well `3.4.19`
